### ISSUE TITLE
Don't log an error if touch is not supported

### ISSUE THREAD

**Issue by flash1293** [kitze/react-long#2]
First of all, awesome library, exactly what I was looking for :)

It would be awesome if you would consider not logging an error if touch is not supported but instead just failing silently. Real-world apps are executed on a wide range of devices (with and without touch support) and the case that touch is not supported is very much expected and not really an "error" of the application.

I'm aware of the possibility of doing the feature-detection myself and only using react-long if touch-support is there, but since in almost all usage scenarios just not doing anything at all if touch isn't available is the desirable behavior, the library could and should take care of this.

Personally I think the warning on top of the readme is enough information at this point.

**Comment by kitze** [comment]
Makes sense.
