### ISSUE TITLE
You should update your npm package and version

### ISSUE THREAD

**Issue by jahooma** [kitze/react-long#6]
Needed the recent fix for calling through to the onTouchStart props passed in, but could not get it with an 'npm update'. Had to copy your source code instead.

**Comment by kitze** [comment]
Just published an update, let me know if it's fine.

**Comment by jahooma** [comment]
Cool, thanks dude!

The release on this site looks good, but when I pull the npm package, it seems like it has the old code even though it is version 1.1.6. Hmm.

Don't worry about it for my sake as we've just copied your new code and it's working, but unless I did something wrong, npm update or install doesn't seem to be fetching the newest code.

Good luck.

**Comment by mayteio** [comment]
@jahooma did you try `rf -rf node_modules && yarn` ?
